#!/bin/bash

node convertBook.js Genesis gen
node convertBook.js Exodus ex
node convertBook.js Leviticus lev
node convertBook.js Numbers num
node convertBook.js Deuteronomy deut
node convertBook.js Joshua josh
node convertBook.js Judges judg
node convertBook.js Ruth ruth
node convertBook.js 1Samuel 1sam
node convertBook.js 2Samuel 2sam
node convertBook.js 1Kings 1kings
node convertBook.js 2Kings 2kings
node convertBook.js 1Chronicles 1chron
node convertBook.js 2Chronicles 2chron
node convertBook.js Ezra ezra
node convertBook.js Nehemiah neh
node convertBook.js Esther est
node convertBook.js Jog job
node convertBook.js Psalms ps
node convertBook.js Proverbs prov
node convertBook.js Ecclesiastes eccles
node convertBook.js SongofSolomon song
node convertBook.js Isaiah isa
node convertBook.js Jeremiah jer
node convertBook.js Lamentations lam
node convertBook.js Ezekiel ezek
node convertBook.js Daniel dan
node convertBook.js Hosea hos
node convertBook.js Joel joel
node convertBook.js Amos amos
node convertBook.js Obadiah obad
node convertBook.js Jonah jonah
node convertBook.js Micah mic
node convertBook.js Nahum nah
node convertBook.js Habakkuk hab
node convertBook.js Zephaniah zeph
node convertBook.js Haggai hag
node convertBook.js Zechariah zech
node convertBook.js Malachi mal
node convertBook.js Matthew matt
node convertBook.js Mark mark
node convertBook.js Luke luke
node convertBook.js John john
node convertBook.js Acts acts
node convertBook.js Romans rom
node convertBook.js 1Corinthians 1cor
node convertBook.js 2Corinthians 2cor
node convertBook.js Galatians gal
node convertBook.js Ephesians eph
node convertBook.js Philippians phil
node convertBook.js Colossians col
node convertBook.js 1Thessalonians 1thess
node convertBook.js 2Thessalonians 2thess
node convertBook.js 1Timothy 1tim
node convertBook.js 2Timothy 2tim
node convertBook.js Titus titus
node convertBook.js Philemon philem
node convertBook.js Hebrews heb
node convertBook.js James james
node convertBook.js 1Peter 1pet
node convertBook.js 2Peter 2pet
node convertBook.js 1John 1john
node convertBook.js 2John 2john
node convertBook.js 3John 3john
node convertBook.js Jude jude
node convertBook.js Revelation rev
